global:
  remained_num: 7
  date_formats:
    - "YYYY-MM-DD"
    - "YYYYMMDD"
    - "YYYY_MM_DD"
  suffixes:
    - ".log"
    - ".txt"

# 此配置文件中无items项目，那么采用结构体中的默认值

jobs:
  - name: "删除示例"
    paths:
      - "/tmp/1"
      - "/tmp/1/2"

  - name: "删除示例2"
    remained_num: 3
    date_formats:
      - "YYYYMMDD"
    suffixes:
      - ".log"
    paths:
      - "/tmp/*/*/*"
